### ISSUE TITLE
Upgrading to Python 3.10

### ISSUE THREAD

**Issue by Swangeon** [honeynet/honeyscanner#28]
## Intro
Upgrading the Honeyscanner project to Python 3.10  from Python 3.9.12 could lead to some advantages over the Python version that Honeyscanner currently uses.

## Benefits
One of the benefits that I see is the new match/case statements that were implemented in 3.10 which could help with situations like the [line 128 of vuln_analyzer.py](https://github.com/honeynet/honeyscanner/blob/main/honeyscanner/passive_attacks/vuln_analyzer/vuln_analyzer.py#L128) which is a if statement of 233 columns long making it hard to read or [lines 88 through 96 of attack_orchestrator.py](https://github.com/honeynet/honeyscanner/blob/main/honeyscanner/passive_attacks/attack_orchestrator.py#L86) where a match/case statement could be used to make it more readable there. Another advantage would be the more robust type-hinting system that adds dictionary key type hints and multi-variate type-hints for function parameters so that the programmer and interpreter know what type each key/parameter is supposed to be.

## Community Feedback
Currently, just from my experience, you can run the program in Python 3.10 with no issues and have it run just fine so I would like some more feedback as to what the community wants to do from here.

Sources below:
- https://www.analyticsvidhya.com/blog/2021/08/differences-between-python-3-10-and-python-3-9-which-you-need-to-know/
- https://analyticsindiamag.com/python-3-9-vs-python-3-10-a-feature-comparison/
- https://realpython.com/python310-new-features/

**Comment by IcyArse** [comment]
Since upgrade to 3.10 should be pretty comfortable, and applying its advantages. Maybe moving further down the line to support 3.11 or 3.12 might be a thought especially with F-string and development in other modules compatibility along with other changes in these versions.

**Comment by Swangeon** [comment]
@IcyArse I agree with your point in upgrading it further, however, I think that we should be careful with how we are upgrading it due to how the developers of Python classify the versions of 3.11 and further to be in the bug fixing phase whereas 3.10 is in its security update phase. 

Sources:
- [Version Lifetimes](https://devguide.python.org/versions/)
- [Python 3.11 Issue Tracker](https://github.com/python/cpython/labels/3.11)

**Comment by aristofanischionis** [comment]
Feel free to submit a PR with your requested updates and I will take a look at it then.
