### ISSUE TITLE
Kippo Docker Container Compatibility Issues

### ISSUE THREAD

**Issue by Swangeon** [honeynet/honeyscanner#30]
## Issue
The Kippo docker container that the main [README.md](https://github.com/honeynet/honeyscanner/blob/main/README.md#configuration)¹ links to download only a container for the linux/arm image of Kippo². While I don't believe that it's a problem with the ARM version being available, I believe that the bigger userbase of x86 computers is something that should be added as an option for testing reasons so that developers and users with an x86 CPU can do quick setup and testing with Kippo like all the other honeypot docker containers.

## Sources
1. [README](https://github.com/honeynet/honeyscanner/blob/main/README.md#configuration)
2. [Kippo Container](https://hub.docker.com/r/aristofanischionis/kippo/tags)

**Comment by aristofanischionis** [comment]
We would be happy if you provided a docker image for x86.
